version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch-browsers

    steps:
      - checkout

      - run:
          name: Install env
          command: |
            make bootstrap
            make install

      - run:
          name: Update data
          command: make update-data

      - run:
          name: Commit changes
          command: |
            git add docs
            git config --global user.email "marc.andre.dufresne@gmail.com"
            git config --global user.name "MarcDufresne"
            git commit -m "Update data"
            git push

workflows:
  version: 2
  build:
    triggers:
      - schedule:
          cron: "0 0,4,8,12,16,20 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
  force:
    jobs:
      - build:
          filters:
            branches:
              only: force
